### TABUADA DE 1 A 10
num = int(input("Digite um número que você gostaria de saber a tabuada; "))
print("-" * 10)
print("{} X {} = {}".format(num, 1, num * 1))
print("{} X {} = {}".format(num, 2, num * 2))
print("{} X {} = {}".format(num, 3, num * 3))
print("{} X {} = {}".format(num, 4, num * 4))
print("{} X {} = {}".format(num, 5, num * 5))
print("{} X {} = {}".format(num, 6, num * 6))
print("{} X {} = {}".format(num, 7, num * 7))
print("{} X {} = {}".format(num, 8, num * 8))
print("{} X {} = {}".format(num, 9, num * 9))
print("{} X {} = {}".format(num, 10, num * 10))
print("-" * 10)